# Generated by Django 5.2.16 on 2026-07-16 12:34

from django.db import migrations, models


def populate_url_parameter(apps, schema_editor):
    Participant = apps.get_model("ddm_participation", "Participant")

    participants = Participant.objects.only("id", "extra_data").all()

    to_update = []
    for participant in participants.iterator():
        extra_data = participant.extra_data
        if isinstance(extra_data, dict) and "url_param" in extra_data:
            url_parameter = extra_data["url_param"]
            participant.url_parameter = url_parameter
            to_update.append(participant)

    Participant.objects.bulk_update(
        to_update, ["url_parameter"], batch_size=500
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_participation', '0002_alter_participant_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='url_parameter',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(
            populate_url_parameter, reverse_code=migrations.RunPython.noop
        ),
    ]
