# Generated by Django 3.2.13 on 2024-10-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_projects', '0001_initial'),
        ('ddm_auth', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='projectaccesstoken',
                    name='project',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_project', to='ddm_projects.donationproject', verbose_name='Donation Project'),
                ),
            ],
            # Reusing an existing table, so do nothing.
            database_operations=[]
        )
    ]
