= Project Logs
:!toc:
:icons: font
:stem: latexmath
:last-update-label!:
:favicon: ddl_favicon_black.svg
:showtitle!:
:page-pagination:

This page describes the implemented exceptions that are logged in a project's exception log.

== Client Side Logs

Exceptions caught on the client side are exceptions and events that occurred in the participants' browser when
donating data or filling out the questionnaire.

=== Data Donation Logs

*INVALID_ZIP* +
_Description:_ Indicates that an uploader expects a ZIP-file but a different file-type was uploaded. +

*ZIP_READ_FAIL* +
_Description:_ Indicates that an error occurred trying to read a ZIP-file.  +

*INVALID_REGEX* +
_Description:_ Indicates that an invalid RegEx was provided as blueprint path. +

*INVALID_RULE_REGEX* +
_Description:_ Indicates that an invalid RegEx was provided as file rule field name. +

*NO_FILE_MATCH* +
_Description:_ Indicates that a ZIP-container did not contain the file as defined on the blueprint. +

*FILE_PROCESSING_FAIL_GENERAL* +
_Description:_ Indicates that an unexpected error occurred during processing of a file's content. +

*STRING_CONVERSION_ERROR* +
_Description:_ Indicates that a file's content could not be converted to a string. +

*NO_EXTRACTION_RULES* +
_Description:_ Indicates that a blueprint has no extraction rules defined (meaning that nothing will be extracted). +

*PARSING_ERROR* +
_Description:_ Indicates that an error occurred when trying to parse a file's content. +

*UNSUPPORTED_BP_FORMAT* +
_Description:_ Indicates that the file type that a blueprint wants to extract is not supported
(currently, unlikely to ever occur - implemented for potential future use cases). +

*MORE_THAN_ONE_KEY_MATCH* +
_Description:_ Indicates that more than one key (or field/variable) contained in a file matched the field name
defined in an extraction rule. +

*EXTRACTION_STATS* +
_Description:_ Contains a summary of the data extraction procedure.
Includes the _number of rows with a missing field_ (nRowsMissingField),
the _number of rows that were filtered out_ (nRowsFilteredOut),
the _total number of extracted rows_ (nRowsTotal), and
_information on how often and which rule fields could not be found in the file_ (noKeyMatches). +

*EXTRACTION_LOG* +
_Description:_ Contains a summary of how many times an extraction rule led to the exclusion of a data row
during the data extraction procedure (is a dictionary where the keys represent the extraction rule IDs and the values the counts). +

*EXTRACTED_FIELDS_MAP* +
_Description:_ Contains a summary of which field names in the extracted files where matched with which
extraction rule field name during the data extraction procedure. +


=== Questionnaire Logs

NOTE: Currently, not implemented. May be implemented in the future.
