exclude: '^docs/|/migrations/'
default_stages: [pre-commit]
minimum_pre_commit_version: "3.2.0"

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: ^mkdocs\.yml$  # Material for MkDocs uses !!python/name: YAML tags
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.27.0'
    hooks:
      - id: django-upgrade
        args: ['--target-version', '5.2']

  - repo: https://github.com/pypa/pip-audit
    rev: v2.10.0
    hooks:
      -   id: pip-audit
          stages: [pre-push]
          files: ^requirements/.*\.txt$
          args: ["-r", "requirements/base.txt", "-r", "requirements/dev.txt"]

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.21
    hooks:
      # Linter
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      # - id: djlint-reformat-django
      - id: djlint-django

#  - repo: local
#    hooks:
#      - id: check-translations
#        name: Check for missing translations
#        language: system
#        entry: bash scripts/check_translations.sh
#        pass_filenames: false
#        types_or: [python, html]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
