# Generated by Django 2.2.13 on 2020-08-25 08:46

import ckeditor.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.PositiveIntegerField(default=1)),
                ('page_type', models.CharField(choices=[('questionpage', 'Question Page'), ('endpage', 'End Page')], max_length=50)),
                ('show_back_button', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surquest.page_set+', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('question_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('question_instruction', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('genericquestion', 'generic question'), ('singlechoicequestion', 'single choice'), ('multichoicequestion', 'multi choice'), ('matrixquestion', 'matrix'), ('differentialquestion', 'differential'), ('listquestion', 'list'), ('transitionquestion', 'transition'), ('openquestion', 'open'), ('fileupload', 'file upload'), ('filefeedback', 'file feedback')], default='genericquestion', max_length=44)),
                ('index', models.PositiveIntegerField(default=1)),
                ('page', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surquest.Page')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surquest.question_set+', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['page__index', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(verbose_name='Questionnaire Slug')),
                ('active', models.BooleanField(default=False)),
                ('accessibility', models.CharField(choices=[('public', 'Public'), ('token', 'Token')], default='Public', max_length=20)),
                ('missing_not_answered', models.IntegerField(default=-77, help_text='Default value if the participant did not answer the question.')),
                ('missing_not_seen', models.IntegerField(default=-66, help_text='Default value if the participant did not shown the question (e.g. because it was filtered out).')),
                ('missing_invalid', models.IntegerField(default=-88, help_text='Default value if the submitted answer to a question is invalid. (e.g. e.g. if the server receives a string for a question that only allows integers).')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('execution_point', models.CharField(choices=[('before', 'before'), ('after', 'after')], max_length=20)),
                ('trigger_type', models.CharField(choices=[('tokengenerator', 'Token Generator'), ('variablesfromdata', 'Variables from Data')], max_length=44)),
                ('execution_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.Page')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surquest.trigger_set+', to='contenttypes.ContentType')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.Questionnaire')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='UploadedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(max_length=10)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('upload_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDataTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DifferentialQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
                ('scale_points', models.PositiveIntegerField(default=5, help_text='The maximum number of scale points is 9.', validators=[django.core.validators.MaxValueValidator(9)])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.CreateModel(
            name='EndPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Page')),
                ('redirect', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(blank=True, help_text='Only required if "redirect" is selected.', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.page',),
        ),
        migrations.CreateModel(
            name='FileFeedback',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
                ('variable_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')])),
                ('need_to_confirm', models.BooleanField(default=False)),
                ('display_upload_table', models.BooleanField(default=False)),
                ('display_upload_stats', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
                ('variable_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')])),
                ('valid_file_types', models.CharField(help_text='Indicate all valid file types, separated by semicolons (e.g. .json; .xlsx). Currently, only .json files are supported.', max_length=100, validators=[django.core.validators.RegexValidator('^(\\s*\\.[0-9a-zA-Z]*;*)*$', 'File types must be separated by a semicolon (;) and must be of the form".filename", where the filename can only contain letters and numbers.')])),
                ('max_filesize', models.IntegerField(default=100000, verbose_name='filesize in kb')),
                ('validation_fields', models.TextField(help_text='List all fields that must be included in the uploaded file, separated by semicolons (e.g. name; date; ...). This serves as a file validation, and the upload will be aborted if the file does not include at least the listed fields.')),
                ('extraction_fields', models.TextField(help_text='List all fields that shall be extracted from the uploaded file, separated by semicolons (e.g. name; date; ...). Only the fields listed here will be stored in the database.')),
                ('requires_consent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.CreateModel(
            name='ListQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
                ('encrypt', models.BooleanField(default=False, help_text='If on, the input is stored in the database in an encrypted form, and not as plain input. If the variable is referenced in a text or description within the questionnaire, the tag "|decrypt" must be added (e.g. [[ var_name|decrypt ]]), otherwise the encrypted value will be displayed.')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.CreateModel(
            name='MatrixQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
                ('scale_repetition', models.PositiveIntegerField(blank=True, help_text='Repeat scale every x lines.', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
                ('variable_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')])),
                ('encrypt', models.BooleanField(default=False)),
                ('display_size', models.CharField(choices=[('small', 'small'), ('large', 'large')], default='small', max_length=10)),
                ('input_format', models.CharField(choices=[('[^0-9\\.]+', 'date'), ('[^0-9]+', 'number'), ('text', 'text')], default='text', max_length=220)),
                ('max_input_length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.CreateModel(
            name='QuestionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Page')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.page',),
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
                ('variable_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.CreateModel(
            name='TokenGenerator',
            fields=[
                ('trigger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Trigger')),
                ('store_in_response', models.BooleanField(default=True)),
                ('variable_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')])),
                ('included_vars', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.trigger',),
        ),
        migrations.CreateModel(
            name='TransitionQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('related_type', models.CharField(max_length=10, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(unique=True)),
                ('current_page', models.IntegerField(blank=True, null=True)),
                ('last_submitted_page', models.IntegerField(blank=True, null=True)),
                ('step_back', models.BooleanField(default=False)),
                ('time_started', models.DateTimeField()),
                ('time_submitted', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.IntegerField(default=-99)),
                ('completed', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token', models.CharField(blank=True, max_length=30, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surquest.Questionnaire')),
            ],
            options={
                'ordering': ['-time_started'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1024)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.QuestionnaireSubmission')),
                ('trigger', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surquest.Trigger')),
                ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='surquest.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional Answer')),
                ('variable_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')])),
                ('index', models.IntegerField()),
                ('value', models.IntegerField(default=-199)),
                ('randomize', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.Question')),
                ('variable', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='surquest.Variable')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')], verbose_name='filter condition name')),
                ('filter_variable_name', models.CharField(max_length=20)),
                ('comparison_object', models.CharField(choices=[('question', 'question'), ('item', 'item')], max_length=10)),
                ('comparison_type', models.CharField(choices=[('equal', '='), ('notequal', '!='), ('bigger', '>'), ('smaller', '<')], max_length=20)),
                ('comparison_value', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('filter_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_filter', to='surquest.Question')),
                ('filter_question_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_filter', to='surquest.QuestionItem')),
                ('target_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_condition', to='surquest.Question')),
                ('target_question_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_condition', to='surquest.QuestionItem')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='variable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='surquest.Variable'),
        ),
        migrations.AddField(
            model_name='page',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.Questionnaire'),
        ),
        migrations.CreateModel(
            name='FilterSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\)\\(,\\s-]*$', 'Only alphanumeric characters, underscores, hyphens and brackets are allowed.')])),
                ('logic', models.CharField(choices=[('show', 'show if'), ('hide', 'hide if')], default='hide', max_length=20)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surquest.Question')),
                ('question_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surquest.QuestionItem')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')])),
                ('source', models.CharField(choices=[('token', 'token'), ('url', 'url parameter')], max_length=30)),
                ('related_parameter', models.CharField(max_length=200)),
                ('required', models.BooleanField(default=False)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.Questionnaire')),
                ('variable', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='surquest.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='VariablesFromData',
            fields=[
                ('trigger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Trigger')),
                ('variable_name_stem', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')])),
                ('variable_name_stem_prev', models.CharField(blank=True, max_length=20, null=True)),
                ('n_variables', models.IntegerField()),
                ('n_variables_prev', models.IntegerField(blank=True, null=True)),
                ('field_to_extract', models.CharField(max_length=255)),
                ('filter_active', models.BooleanField(default=False)),
                ('filter_condition', models.CharField(max_length=255)),
                ('related_upload_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.FileUpload')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.trigger',),
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.UniqueConstraint(fields=('name', 'questionnaire'), name='unique_varname_per_questionnaire'),
        ),
        migrations.AddField(
            model_name='tokengenerator',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.Questionnaire'),
        ),
        migrations.AddField(
            model_name='tokengenerator',
            name='variable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='surquest.Variable'),
        ),
        migrations.AddField(
            model_name='questionscale',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.MatrixQuestion'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('name', 'questionnaire'), name='unique_name_per_questionnaire'),
        ),
        migrations.AddField(
            model_name='filefeedback',
            name='related_filequestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.FileUpload'),
        ),
    ]
