# Generated by Django 3.2.9 on 2021-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireaccesstoken',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triggertask',
            name='execution_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeddata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
