# Generated by Django 2.2.13 on 2020-09-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTrigger',
            fields=[
                ('trigger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Trigger')),
                ('from_email', models.CharField(default='contact@digital-meal.ch', max_length=254, verbose_name='Sender')),
                ('to_email', models.CharField(blank=True, max_length=254, null=True, verbose_name='Receiver')),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.trigger',),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='trigger_type',
            field=models.CharField(choices=[('tokengenerator', 'Token Generator'), ('variablesfromdata', 'Variables from Data'), ('emailtrigger', 'E-Mail Trigger')], max_length=44),
        ),
    ]
