# Generated by Django 3.2.9 on 2022-02-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0002_auto_20211220_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DonationBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_file_type', models.CharField(choices=[('json', 'Json Type')], default='json', max_length=10)),
                ('exp_fields', models.JSONField()),
                ('extracted_fields', models.JSONField()),
            ],
        ),
    ]
