# Generated by Django 2.2.13 on 2020-09-01 08:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0002_auto_20200901_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscores and hyphens are allowed.')])),
                ('valid_file_types', models.CharField(help_text='Indicate all valid file types, separated by semicolons (e.g. .json; .xlsx). Currently, only .json files are supported.', max_length=100, validators=[django.core.validators.RegexValidator('^(\\s*\\.[0-9a-zA-Z]*;*)*$', 'File types must be separated by a semicolon (;) and must be of the form".filename", where the filename can only contain letters and numbers.')])),
                ('max_filesize', models.IntegerField(default=100000, verbose_name='filesize in kb')),
                ('validation_fields', models.TextField(help_text='List all fields that must be included in the uploaded file, separated by semicolons (e.g. name; date; ...). This serves as a file validation, and the upload will be aborted if the file does not include at least the listed fields.')),
                ('extraction_fields', models.TextField(help_text='List all fields that shall be extracted from the uploaded file, separated by semicolons (e.g. name; date; ...). Only the fields listed here will be stored in the database.')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Question')),
                ('upload_mode', models.CharField(choices=[('singlefile', 'Single File'), ('zipfile', '.zip File')], max_length=20)),
                ('max_filesize', models.IntegerField(default=100000, verbose_name='filesize in kb')),
                ('requires_consent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.question',),
        ),
        migrations.AlterField(
            model_name='filefeedback',
            name='related_filequestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.FileUploadItem'),
        ),
        migrations.AlterField(
            model_name='variablesfromdata',
            name='related_upload_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surquest.FileUploadItem'),
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AddField(
            model_name='fileuploaditem',
            name='file_upload_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surquest.FileUploadQuestion'),
        ),
    ]
