# Generated by Django 3.2.9 on 2022-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0003_datadonation_donationblueprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationblueprint',
            name='exp_file_type',
        ),
        migrations.AddField(
            model_name='donationblueprint',
            name='exp_file_format',
            field=models.CharField(choices=[('json', 'Json Format')], default='json', max_length=10),
        ),
    ]
