# Generated by Django 3.2.9 on 2022-02-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0004_auto_20220214_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZippedBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='donationblueprint',
            name='name',
            field=models.CharField(default='blueprint name', max_length=250),
            preserve_default=False,
        ),
    ]
