# Generated by Django 2.2.13 on 2020-09-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0004_fileuploaditem_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploaditem',
            name='expected_filename',
            field=models.CharField(blank=True, help_text='Optional: Specify the name of the uploaded file. Leave empty if the file contents should be matched without checking the file name. Currently only applicable to zip uploads.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fileuploadquestion',
            name='upload_mode',
            field=models.CharField(choices=[('singlefile', 'Single File'), ('zipfile', '.zip File')], default='singlefile', max_length=20),
        ),
    ]
