# Generated by Django 3.2.9 on 2022-02-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0005_auto_20220214_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationblueprint',
            name='regex_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationblueprint',
            name='zip_blueprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddm.zippedblueprint'),
        ),
    ]
