# Generated by Django 2.2.13 on 2020-09-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0005_auto_20200901_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfilter',
            name='filter_upload_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_filter', to='surquest.FileUploadItem'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('genericquestion', 'generic question'), ('singlechoicequestion', 'single choice'), ('multichoicequestion', 'multi choice'), ('matrixquestion', 'matrix'), ('differentialquestion', 'differential'), ('listquestion', 'list'), ('transitionquestion', 'transition'), ('openquestion', 'open'), ('fileuploadquestion', 'file upload question'), ('filefeedback', 'file feedback')], default='genericquestion', max_length=44),
        ),
        migrations.AlterField(
            model_name='questionfilter',
            name='comparison_object',
            field=models.CharField(choices=[('question', 'question'), ('item', 'item'), ('uploaditem', 'upload item')], max_length=10),
        ),
    ]
