# Generated by Django 3.2.9 on 2022-02-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0006_auto_20220214_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationblueprint',
            old_name='exp_fields',
            new_name='expected_fields',
        ),
    ]
