# Generated by Django 2.2.13 on 2020-09-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0006_auto_20200903_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='enable_continuation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokengenerator',
            name='include_session_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tokengenerator',
            name='included_vars',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
