# Generated by Django 2.2.13 on 2020-10-29 11:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0007_auto_20200909_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField()),
                ('execution_type', models.CharField(max_length=50)),
                ('execution_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='execution_delay',
            field=models.IntegerField(default=0, help_text='Execution delay time in minutes.'),
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='execution_time',
            field=models.CharField(choices=[('immediately', 'immediately'), ('delayed', 'delayed')], default='immediately', max_length=20),
        ),
    ]
