# Generated by Django 3.2.9 on 2022-02-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0007_rename_exp_fields_donationblueprint_expected_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadonation',
            name='blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddm.donationblueprint'),
        ),
        migrations.AddField(
            model_name='datadonation',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datadonation',
            name='status',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datadonation',
            name='time',
            field=models.DateTimeField(default='2022-02-16T12:53:56.646217'),
            preserve_default=False,
        ),
    ]
