# Generated by Django 3.2.9 on 2022-02-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0008_auto_20220216_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True, verbose_name='External Project Slug')),
            ],
        ),
    ]
