# Generated by Django 2.2.13 on 2020-10-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0008_auto_20201029_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddata',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surquest.Questionnaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadeddatatemp',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surquest.Questionnaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileuploaditem',
            name='expected_filename',
            field=models.CharField(blank=True, help_text='Optional: Specify the name of the uploaded file. Leave empty if the file contents should be matched without checking the file name. If multiple filenames should be accepted, separate the filenemas with a semicolon (;). Currently only applicable to zip uploads.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='missing_invalid',
            field=models.IntegerField(default=-88, help_text='Default value if the submitted answer to a question is invalid. (e.g. if the server receives a string for a question that only allows integers).'),
        ),
    ]
