# Generated by Django 2.2.13 on 2020-10-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0009_auto_20201029_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionitem',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='answer_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional Answer'),
        ),
    ]
