# Generated by Django 3.2.9 on 2022-02-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0010_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationblueprint',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddm.donationproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zippedblueprint',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddm.donationproject'),
            preserve_default=False,
        ),
    ]
