# Generated by Django 3.2.13 on 2022-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0011_auto_20220830_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationproject',
            name='contact_information',
            field=models.TextField(null=True, verbose_name='Contact information'),
        ),
        migrations.AddField(
            model_name='donationproject',
            name='data_protection_statement',
            field=models.TextField(null=True, verbose_name='Data Protection Statement'),
        ),
    ]
