# Generated by Django 3.2.9 on 2022-02-18 14:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ddm', '0011_auto_20220218_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='QItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('label_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.IntegerField()),
                ('value', models.IntegerField()),
                ('randomize', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='QScalePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.IntegerField()),
                ('add_border', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('generic', 'Generic Question'), ('single_choice', 'Single Choice Question'), ('multi_choice', 'Multi Choice Question'), ('matrix', 'Matrix Question'), ('semantic_diff', 'Semantic Differential'), ('open', 'Open Question'), ('transition', 'Transition Block')], default='generic', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('index', models.PositiveIntegerField(default=1)),
                ('variable_name', models.SlugField()),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddm.donationblueprint')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ddm.questionbase_set+', to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddm.donationproject')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestionAlt',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ddm.questionbase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ddm.questionbase',),
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestionAlt',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ddm.questionbase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ddm.questionbase',),
        ),
        migrations.DeleteModel(
            name='CleanUploadDataTrigger',
        ),
        migrations.DeleteModel(
            name='DifferentialQuestion',
        ),
        migrations.DeleteModel(
            name='EmailTrigger',
        ),
        migrations.DeleteModel(
            name='EndPage',
        ),
        migrations.DeleteModel(
            name='ExternalVariable',
        ),
        migrations.DeleteModel(
            name='FileFeedback',
        ),
        migrations.DeleteModel(
            name='FileUploadItem',
        ),
        migrations.DeleteModel(
            name='FileUploadQuestion',
        ),
        migrations.DeleteModel(
            name='FilterCondition',
        ),
        migrations.DeleteModel(
            name='FilterSequence',
        ),
        migrations.DeleteModel(
            name='ListQuestion',
        ),
        migrations.DeleteModel(
            name='MatrixQuestion',
        ),
        migrations.DeleteModel(
            name='MultiChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='OpenQuestion',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionItem',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='QuestionnaireAccessToken',
        ),
        migrations.DeleteModel(
            name='QuestionnaireResponse',
        ),
        migrations.DeleteModel(
            name='QuestionnaireSubmission',
        ),
        migrations.DeleteModel(
            name='QuestionPage',
        ),
        migrations.DeleteModel(
            name='QuestionScale',
        ),
        migrations.DeleteModel(
            name='SingleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='TokenGenerator',
        ),
        migrations.DeleteModel(
            name='TransitionQuestion',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
        migrations.DeleteModel(
            name='UploadedData',
        ),
        migrations.DeleteModel(
            name='UploadedDataTemp',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
        migrations.DeleteModel(
            name='VariablesFromData',
        ),
        migrations.AddField(
            model_name='qscalepoint',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddm.questionbase'),
        ),
        migrations.AddField(
            model_name='qitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddm.questionbase'),
        ),
        migrations.AddConstraint(
            model_name='questionbase',
            constraint=models.UniqueConstraint(fields=('variable_name', 'project'), name='unique_varname_per_project'),
        ),
        migrations.AddConstraint(
            model_name='qscalepoint',
            constraint=models.UniqueConstraint(fields=('index', 'question'), name='unique_index_per_question'),
        ),
    ]
