# Generated by Django 2.2.13 on 2020-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0011_fileuploadquestion_variable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixquestion',
            name='scale_repetition',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Repeat scale every x lines.', null=True),
        ),
    ]
