# Generated by Django 2.2.13 on 2020-11-08 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0012_auto_20201105_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanUploadDataTrigger',
            fields=[
                ('trigger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surquest.Trigger')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surquest.trigger',),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='trigger_type',
            field=models.CharField(choices=[('tokengenerator', 'Token Generator'), ('variablesfromdata', 'Variables from Data'), ('emailtrigger', 'E-Mail Trigger'), ('cleanuploaddata', 'Clean Upload Data')], max_length=44),
        ),
    ]
