# Generated by Django 2.2.13 on 2020-11-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0013_auto_20201108_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionscale',
            name='add_border',
            field=models.BooleanField(default=False),
        ),
    ]
