# Generated by Django 3.2.9 on 2022-02-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0014_matrixquestion_semanticdifferential_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='display',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large')], default='large', max_length=20),
        ),
    ]
