# Generated by Django 2.2.13 on 2020-11-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0014_questionscale_add_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfilter',
            name='filter_ext_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_filter', to='surquest.ExternalVariable'),
        ),
        migrations.AlterField(
            model_name='questionfilter',
            name='comparison_object',
            field=models.CharField(choices=[('question', 'question'), ('item', 'item'), ('uploaditem', 'upload item'), ('externalvar', 'external variable')], max_length=10),
        ),
    ]
