# Generated by Django 3.2.9 on 2022-02-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0015_openquestion_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrixquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='multichoicequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semanticdifferential',
            options={},
        ),
        migrations.AlterModelOptions(
            name='singlechoicequestion',
            options={},
        ),
        migrations.AddField(
            model_name='matrixquestion',
            name='randomize_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='randomize_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semanticdifferential',
            name='randomize_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='randomize_items',
            field=models.BooleanField(default=False),
        ),
    ]
