# Generated by Django 2.2.13 on 2020-12-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surquest', '0015_auto_20201117_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfilter',
            name='comparison_object',
            field=models.CharField(choices=[('question', 'question'), ('item', 'item'), ('uploaditem', 'upload item'), ('extvar', 'external variable')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questionfilter',
            name='filter_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_filter', to='surquest.Question'),
        ),
    ]
