# Generated by Django 3.2.9 on 2022-02-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0016_auto_20220218_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadonation',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddm.participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datadonation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddm.donationproject'),
            preserve_default=False,
        ),
    ]
