# Generated by Django 3.2.9 on 2022-02-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0018_auto_20220222_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='responses',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
