# Generated by Django 3.2.9 on 2022-02-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0019_questionnaireresponse_responses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireresponse',
            old_name='responses',
            new_name='data',
        ),
    ]
