# Generated by Django 3.2.9 on 2022-03-01 12:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0020_rename_responses_questionnaireresponse_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationproject',
            name='intro_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationproject',
            name='outro_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
