# Generated by Django 3.2.9 on 2022-03-02 09:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0021_auto_20220301_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('index', models.PositiveIntegerField(default=1)),
                ('blueprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddm.donationblueprint')),
                ('zip_blueprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddm.zippedblueprint')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddConstraint(
            model_name='donationinstruction',
            constraint=models.UniqueConstraint(fields=('index', 'blueprint'), name='unique_index_per_blueprint'),
        ),
        migrations.AddConstraint(
            model_name='donationinstruction',
            constraint=models.UniqueConstraint(fields=('index', 'zip_blueprint'), name='unique_index_per_zipblueprint'),
        ),
    ]
