# Generated by Django 3.2.13 on 2023-12-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0044_auto_20231203_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingrule',
            name='comparison_operator',
            field=models.CharField(blank=True, choices=[('', 'Keep Field'), ('==', 'Equal (==)'), ('!=', 'Not Equal (!=)'), ('>', 'Greater than (>)'), ('<', 'Smaller than (<)'), ('>=', 'Greater than or equal (>=)'), ('<=', 'Smaller than or equal (<=)'), ('regex-delete-match', 'Delete match (regex)'), ('regex-replace-match', 'Replace match (regex)'), ('regex-delete-row', 'Delete row when match (regex)')], default=None, max_length=24, null=True, verbose_name='Extraction Operator'),
        ),
    ]
