# Generated by Django 3.2.13 on 2024-10-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0051_auto_20241025_1209'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='donationblueprint',
                    name='file_uploader',
                ),
                migrations.RemoveField(
                    model_name='donationblueprint',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='donationinstruction',
                    name='file_uploader',
                ),
                migrations.RemoveField(
                    model_name='fileuploader',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='processingrule',
                    name='blueprint',
                ),
                migrations.DeleteModel(
                    name='DataDonation',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='DataDonation',
                    table='ddm_datadonation_datadonation'
                ),
            ]
        )
    ]
