= Documentation for Researchers
:!toc:
:icons: font
:stem: latexmath
:last-update-label!:
:favicon: ddl_favicon_black.svg
:showtitle!:


This part of the documentation is addressed at the _users_ of the Data Donation Module (i.e., the researchers) and will explain:

- How to set up a data donation project.
- How to monitor an ongoing data donation project.
- How to download and work with the collected data.

It is assumed that a server with DDM set up on it is running.
Readers interested in setting up a server to run DDM for institutional use or their own research should turn to the xref:for_admins.adoc[Documentation for Administrators].
For a general introduction to the module, see xref:index.adoc[this page].


== Setting Up a Data Donation Project

=== Creating a Project

To set up a new data donation project, got to the `/projects/` page and click on "+ Create New Project".
On the project creation page, you will be presented with the following options to configure your project:

Project Name:: Name of the project. Visible to participants in the browser's title bar or a page's tab.

External Project Slug:: Identifier that is used to expose the project to participants (e.g, https://root.url/project-slug ).

Contact Information:: Contact information of the researcher responsible for the project.
Is linked in the footer of the donation interface and can be viewed by data donors at any stage of the data donation process.

Data Protection Statement:: Data protection statement that describes how the data is processed.
Is linked in the footer of the donation interface and can be viewed by data donors at any stage of the data donation process.

Super Secret:: When creating a "super secret" project, you will have to provide
a password, which will be used to encrypt all collected data donations and survey responses
(for more information on how collected data is encrypted, see xref:topics/encryption.adoc[here]).
This password will not be saved by the application, and the data collected for
this project can only be encrypted by entering the password that was used as a super secret
when the project was created.
Please note that there is no way to recover or reset this password if it is lost.
Furthermore, also note that making a project "super secret" will limit the
functionality of the module: it won’t be possible to create followup questions based on the data donation
(i.e., data points from the data donation cannot be referenced in a question).


=== The Project Hub

Once a project is created, you will be redirected to the "Project Hub".
From here, you can access all settings and information that are relevant for your data donation project.
It consists of four main areas:

1. Project Details

2. Project Configuration

3. Data Center

4. Danger Zone



=== Editing Project Details

==== Base Settings

Project Name:: Name of the project. Visible to participants in the browser's title bar or a page's tab.

External Project Slug:: Identifier that is used to expose the project to participants (e.g, https://root.url/project-slug ).

==== Public Project Information

Contact Information:: Contact information of the researcher responsible for the project.
Is linked in the footer of the donation interface and can be viewed by data donors at any stage of the data donation process.

Data Protection Statement:: Data protection statement that describes how the data is processed.
Is linked in the footer of the donation interface and can be viewed by data donors at any stage of the data donation process.

==== Redirect Configuration

Redirect enabled:: Enable or disable the redirection of your participants when they have completed your project.
If enabled, a redirect button will be displayed on the data donation end page that redirects to the URL defined in the `Redirect target` setting.

Redirect target:: URL to which participants will redirected (only required if `redirect` is enabled).
The redirect URL can include variables that are populated with the respective values. Currently, the following variables are supported:
An extracted URL parameter (see above), the participant id (as ``ddm_participant_id``), or the project id (as ``ddm_project_id``).
Use the following syntax to include variables in the redirect target: e.g. ``https://redirect.url?param={{URLParameter}}&participant={{ddm_participant_id}}&project={{ddm_project_id}}``



==== URL Parameter Extraction

URL parameter extraction enabled:: Enable or disable whether URL parameters should be extracted when participants access the project's briefing page.

Expected URL parameter:: Provide a string containing the parameters that should be extracted. Separate multiple parameters with a semikolon (e.g., "parameter_A;parameter_B").

General behavior: // TODO: Describe general behavior (where are the extracted values saved, what is the default behavior when a URL parameter is not present)


==== Project Appearance

Header Image Left/Header Image Right:: Upload an image that will be displayed in the header of your project (e.g., an institution or project logo).


=== Editing Project Configuration

The structure of the Project Configuration follows the steps of the prototypical
data donation process. It consists of the following sections:

1. Welcome Page: Define what is displayed to participants when they enter your project.
2. Data Donation: Define the expected data donations, extraction rules, and donation instructions.
3. Questionnaire: Define questions that will be shown to participants after they have donated their data.
4. End Page: Define what is displayed when participants reach the end of the data donation.

==== Briefing

Welcome Page Text:: Text displayed to participants on the briefing page.

Briefing consent enabled:: If briefing consent is enabled, participants will
have to explicitly indicate their consent at the bottom of the briefing page before
they can continue. If a participant does not indicate active consent, they will
be redirected to the debriefing page. // TODO: Check this behavior.

Briefing consent label yes/Briefing consent label no:: The labels displayed to
participants to indicate consent ("briefing consent label yes") or reject
consent ("briefing consent label no").


==== Data Donation

The data donation is organized in `File Uploaders` and `Donation Blueprints`.

A "File Uploader" corresponds to the file that is expected to be uploaded.
This file can either be a single file (e.g., a JSON file) or a ZIP container.

For each File Uploader, a set of `Instructions` for participants can be defined
that describe how they can access and upload the requested file.

Each uploader has one or multiple associated `Donation Blueprints`.
A Donation Blueprint defines how the data contained in a single file
(e.g., the uploaded file in the case of a single file upload, or a file contained
in the ZIP container in the case of a ZIP upload) is extracted.

The data donation step can incorporate multiple File Uploaders.

===== Configure File Uploader

Name:: Name of the File Uploader. Will be publicly visible to participants in the header of the file uplaoder.

Upload Type:: Either "single file" or "zip file".

Index:: The position of the file uploader on the data donation page.
Only relevant if multiple file uploaders are displayed – file uploaders with a
lower index will be displayed closer to the top of the page.

Associated Donation Blueprints:: The donation blueprints that apply to the expected file(s) collected with the file uploader.


===== Configure Instructions

Donation Instructions consist of one or multiple instruction pages.
Instruction pages are displayed as a slide show at the top of file uploader.
For each instruction page, the following can be configured:

Text:: The instruction text displayed to the participants.
By default, researchers can also upload and include images or gifs to guide
participants through the data donation process in this field (video upload is not supported -
but videos hosted externally can still be embedded).  //TODO: Check if video can be embedded without problems.

Index:: The position of the page in the slideshow.

===== Configure Donation Blueprint

Name:: Name of the expected data donations. Will be publicly visible to participants.
Therefore, it is important to define a meaningful name.

Expected file format:: The file format of the expected data donation. Currently, only JSON and CSV is implemented.

Associated File Uploader:: The `File Uploader` for which the blueprint will be applied.

Regex path:: Here, the path where the file is expected to be located within a ZIP file is defined.
Only necessary, if the Donation Blueprint is part of a Blueprint Container.  // TODO: Check if this has already been implemented correctly

Expected fields:: The fields that must be contained in the donated file. If a file does not contain
one or more of the fields defined here, it will not be accepted as a donation.
Put the field names in double quotes (") and separate them with commas ("Field A", "Field B").

==== Questionnaire

Researchers can optionally define a questionnaire consisting of one or more pages, each consisting of one or more questions.
The questions will be displayed after the data donation.

Currently, the following question types are implemented:

* Single Choice Question
* Multi Choice Question
* Matrix Question
* Semantic Differential
* Open Question
* Transition Block (plain text, without any response options for the participant)

Depending on the question types, the following attributes can be configured:

Name:: Question name - only used for internal organisation.

Blueprint (optional):: If associated to a blueprint, the data extracted by
this blueprint for a given participant is available to be included in the question text
(see [LOCATION] for more information on how to include data in question texts). // TODO: Add link.
If the associated blueprint did not extract any data, the question will not be displayed.
If a question should always be displayed, select the option "General Question" here.

Page:: Number of the page on which the question should be displayed.

Text:: The question text that is displayed to participants.  // TODO: Extend description to explain inclusion of donated data.

Required:: If a question is marked as required, the application will show a
hint to the participant if they missed to answer this question.
This hint will only be shown once. This means that if a participant chooses to
ignore the hint and clicks on 'continue', they are able to skip a required question.

Randomize items:: Enable or disable randomization of items.

Question Items:: The items that will be displayed in the answer part of the question.

Scale Configuration:: Configure how the scale displayed to participants to rate items will look like
(only for Matrix Question and Semantic Differential).


[TIP]
====
*How to Include Donated Data in a Question*

It is possible to include information contained in the donated data or related to the participant in the question text.
Questions that should integrate this behaviour must be linked to a donation blueprint
The donated data related to the associated blueprint will then be available as a
context variable an can be referenced in the question body as follows:
`Display donated data: {{ data }}. Display participant data: {{ participant }}.`

For this, DDM utilizes the `Django template engine <https://docs.djangoproject.com/en/3.2/topics/templates/>`_.
The donated data will be available as a template variable "data" in the question text definition.
This variable can be combined flexibly with Django's `built-in template tags and filters <https://docs.djangoproject.com/en/3.2/ref/templates/builtins/>`_.

// TODO: Include Example.

// TODO: Include a list of accessible template features.
====


==== Debriefing

End page text:: Text displayed to participants on the briefing page.


=== Data Center

In the Data Center, you can find options to `A` access the collected data,
`B` access the project logs, and `C` find some general field statistics about the progress of your project.

==== Data Download: Accessing Collected Data Donations

A) Internal Download

B) External Download via API

// TODO: Add Example with R

// TODO: Add Example with Python

==== Data Structure


==== Project Log: Monitoring an on-going Project

// TODO: Describe Exception Logs.

==== Participation Statistics

// TODO: Describe.



=== Danger Zone

Here, you can find all options that affect the data collected in the course of your project:

==== Reset Project Data

With this option, you can delete all data collected for a given project.

==== Delete Participant

You can delete the data for a given participant by providing their external participation id.
// TODO: Explain this function further.

==== Delete Project

With this option you can delete the current project. This will also delete all associated data.
