= DDM Documentation
:!toc:
:icons: font
:stem: latexmath
:last-update-label!:
:favicon: static/img/ddl_favicon_black.svg

*DDM* (Data Donation Module) is an open-source Django/web application that helps researchers to
set up data donation projects and to collect data donations for academic research.

The application is intended to be hosted at an institutional level (e.g., a university, a university division, or a research conglomerate)
as it provides the possibility to host multiple independent data donation projects simultaneously.
Nevertheless, it is also possible to use it for single projects.

It is developed by the Media Use and Effects Division at the University of Zurich.
The Data Donation Module is embedded in a larger initiative of the University of Zurich and the Digital
Society Initiative to strengthen the exchange about the topic of data donations and
promote this data collection approach. For more information, visit https://datadonation.uzh.ch.

NOTE: This project is currently under active development.

== Documentation Structure

Different parts of the documentation are targeted at different user groups of the application.

*xref:for_researchers.adoc[Documentation for Researchers]*: This section is for researchers who use DDM to set up their data donation projects on an
existing application server.

*xref:for_admins.adoc[Documentation for Administrator]*: This section is for server administrators who want to set up a server to host DDM.

*xref:for_developers.adoc[Documentation for Developers]*: This section is for developers who want to contribute to the development of DDM or want
to fork and extend DDM on their own.

Furthermore, the section *xref:topic_references.adoc[Topic References]* contains more detailed information on various specialized topics.

