# Generated by Django 4.2.16 on 2025-03-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_questionnaire', '0008_openquestion_input_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scalepoint',
            old_name='add_border',
            new_name='secondary_point',
        ),
    ]
