# Generated by Django 4.2.16 on 2025-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_questionnaire', '0010_rename_label_scalepoint_input_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openquestion',
            options={},
        ),
        migrations.AddField(
            model_name='openquestion',
            name='multi_item_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openquestion',
            name='randomize_items',
            field=models.BooleanField(default=False),
        ),
    ]
