# Generated by Django 5.2.10 on 2026-01-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_questionnaire', '0012_questionnaireresponse_questionnaire_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transition',
            options={},
        ),
        migrations.AlterField(
            model_name='filtercondition',
            name='source_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
