# Generated by Django 4.2.16 on 2025-03-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ddm_questionnaire', '0012_filtercondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercondition',
            name='target_content_type',
            field=models.ForeignKey(help_text='The target question/question item to which this filter applies.', on_delete=django.db.models.deletion.CASCADE, related_name='filter_target', to='contenttypes.contenttype'),
        ),
    ]
