# Generated by Django 4.2.16 on 2025-04-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_questionnaire', '0013_alter_filtercondition_target_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='questionnaire_config',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddConstraint(
            model_name='filtercondition',
            constraint=models.UniqueConstraint(fields=('target_content_type', 'target_object_id', 'index'), name='unique_index_per_target'),
        ),
    ]
