# Generated by Django 5.2.10 on 2026-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_questionnaire', '0013_alter_transition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercondition',
            name='source_identifier',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='label_alt',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Label Right'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scalepoint',
            name='heading_label',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scalepoint',
            name='input_label',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
