# Generated by Django 5.2.16 on 2026-08-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_questionnaire', '0014_alter_filtercondition_source_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='max_number_value',
            field=models.IntegerField(blank=True, default=None, help_text='Participants must enter a number less than or equal to this value. If empty, no maximum input value restriction is enforced.', null=True, verbose_name='Maximum input value'),
        ),
        migrations.AddField(
            model_name='openquestion',
            name='min_input_length',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Participants' input must be of at least this length. If empty, no minimal input length restriction is enforced.", null=True, verbose_name='Minimum input length'),
        ),
        migrations.AddField(
            model_name='openquestion',
            name='min_number_value',
            field=models.IntegerField(blank=True, default=None, help_text='Participants must enter a number greater than or equal to this value. If empty, no minimum input value restriction is enforced.', null=True, verbose_name='Minimum input value'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='max_input_length',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Participants' input cannot exceed this length. If empty, no input length restriction is enforced.", null=True, verbose_name='Maximum input length'),
        ),
    ]
