# Generated by Django 5.2.16 on 2026-08-08 19:13

from django.db import migrations, models


def reassign_requirement_level(apps, schema_editor):
    QuestionBase = apps.get_model("ddm_questionnaire", "QuestionBase")

    questions = list(QuestionBase.objects.only("id", "required"))
    for q in questions:
        q.requirement_level = "soft_required" if q.required else "not_required"

    QuestionBase.objects.bulk_update(questions, ["requirement_level"], batch_size=500)


def reverse_reassign_requirement_level(apps, schema_editor):
    QuestionBase = apps.get_model("ddm_questionnaire", "QuestionBase")

    questions = list(QuestionBase.objects.only("id", "requirement_level"))
    for q in questions:
        q.required = q.requirement_level in ("soft_required", "hard_required")

    QuestionBase.objects.bulk_update(questions, ["required"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_questionnaire', '0015_openquestion_max_number_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbase',
            name='requirement_level',
            field=models.CharField(choices=[('not_required', 'Not required'), ('soft_required', 'Soft'), ('hard_required', 'Hard')], default='not_required', help_text='Not required: a response is optional. Soft: if missing, a warning is shown once but can be dismissed. Hard: a response is required before proceeding.', max_length=20),
        ),
        migrations.RunPython(
            reassign_requirement_level, reverse_code=reverse_reassign_requirement_level
        ),
        migrations.RemoveField(
            model_name='questionbase',
            name='required',
        ),
    ]
