# Generated by Django 5.2.16 on 2026-08-09 15:00

from django.db import migrations, models


def deduplicate_responses(apps, schema_editor):
    """Keep only the most recent QuestionnaireResponse per (project, participant).

    Needed before the unique constraint below can be added safely: under the
    old create-only save behavior, a double-submit (or similar edge case)
    could have left duplicate rows in any existing database.
    """
    QuestionnaireResponse = apps.get_model('ddm_questionnaire', 'QuestionnaireResponse')
    seen = set()
    for response in QuestionnaireResponse.objects.order_by(
        'project_id', 'participant_id', '-time_submitted'
    ):
        key = (response.project_id, response.participant_id)
        if key in seen:
            response.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_participation', '0003_participant_url_parameter'),
        ('ddm_projects', '0009_donationproject_background_color_and_more'),
        ('ddm_questionnaire', '0016_remove_questionbase_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(deduplicate_responses, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='questionnaireresponse',
            constraint=models.UniqueConstraint(fields=('project', 'participant'), name='unique_questionnaireresponse_per_participant'),
        ),
    ]
