# Generated by Django 4.2.16 on 2025-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0005_alter_donationblueprint_csv_delimiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadonation',
            name='consent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
