# Generated by Django 4.2.16 on 2025-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0006_alter_datadonation_consent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationblueprint',
            options={'ordering': ['display_position', 'pk']},
        ),
        migrations.AddField(
            model_name='donationblueprint',
            name='display_position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
