# Generated by Django 4.2.16 on 2026-01-28 16:59

import ddm.core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0007_alter_donationblueprint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploader',
            name='extract_nested_zips',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileuploader',
            name='extraction_depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='regex_path',
            field=models.TextField(blank=True, help_text='The path where the file is expected to be located in the uploaded ZIP folder. You can use Regex to, e.g., add wildcard characters or to match files in different languages. Consult the documentation for some examples.', null=True, validators=[ddm.core.utils.validators.validate_regex_pattern], verbose_name='File path'),
        ),
    ]
