# Generated by Django 5.2.10 on 2026-01-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0008_fileuploader_extract_nested_zips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintFilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('is_regex', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddm_datadonation.donationblueprint')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
