# Generated by Django 5.2.10 on 2026-01-30 15:51

from django.db import migrations


def migrate_regex_paths(apps, schema_editor):
    DonationBlueprint = apps.get_model('ddm_datadonation', 'DonationBlueprint')
    FilePath = apps.get_model('ddm_datadonation', 'BlueprintFilePath')

    for blueprint in DonationBlueprint.objects.exclude(regex_path__isnull=True).exclude(regex_path=''):
        FilePath.objects.create(
            blueprint=blueprint,
            path=blueprint.regex_path,
            is_regex=True,  # assuming all existing paths used regex
            priority=0,
        )


def reverse_migration(apps, schema_editor):
    DonationBlueprint = apps.get_model('ddm_datadonation', 'DonationBlueprint')
    FilePath = apps.get_model('ddm_datadonation', 'BlueprintFilePath')

    for file_path in FilePath.objects.all():
        file_path.blueprint.regex_path = file_path.path
        file_path.blueprint.save()
        file_path.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0009_filepath'),
    ]

    operations = [
        migrations.RunPython(migrate_regex_paths, reverse_migration),
    ]
