# Generated by Django 5.2.10 on 2026-01-31 11:58

import django.core.validators
from django.db import migrations, models
from django.db.models import F


def copy_blueprint_field_values(apps, schema_editor):
    DonationBlueprint = apps.get_model('ddm_datadonation', 'DonationBlueprint')
    DonationBlueprint.objects.update(display_name=F('name'))


def copy_uploader_field_values(apps, schema_editor):
    FileUploader = apps.get_model('ddm_datadonation', 'FileUploader')
    FileUploader.objects.update(display_name=F('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0010_migrate_regex_path_to_filepath'),
        ('ddm_projects', '0007_alter_donationproject_custom_uploader_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprintfilepath',
            options={'ordering': ['priority', 'path']},
        ),
        migrations.AlterModelOptions(
            name='fileuploader',
            options={'ordering': ['index', 'pk']},
        ),
        migrations.AddField(
            model_name='donationblueprint',
            name='display_name',
            field=models.CharField(default='', help_text='Public name of the blueprint (displayed to participants)', max_length=250),
            preserve_default=False,
        ),
        migrations.RunPython(copy_blueprint_field_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fileuploader',
            name='name',
            field=models.CharField(default='', max_length=250, blank=False, help_text='Internal name for this File Uploader.'),
        ),
        migrations.AddField(
            model_name='fileuploader',
            name='display_name',
            field=models.CharField(default='', help_text='Public name of the File Uploader (displayed to participants)', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='csv_delimiter',
            field=models.CharField(blank=True, default='', help_text='The character that separates values in the CSV.', max_length=10),
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='description',
            field=models.TextField(help_text='Blueprint description visible for participants.', null=True),
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='expected_fields',
            field=models.TextField(help_text='Comma-separated, in double quotes: <code>"Field A", "Field B"</code>', validators=[django.core.validators.RegexValidator('^((["][^"]+["]))(\\s*,\\s*((["][^"]+["])))*[,\\s]*$', message='Field must contain one or multiple comma separated strings. Strings must be enclosed in double quotes ("string").')]),
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='expected_fields_regex_matching',
            field=models.BooleanField(default=False, help_text='Select if you use regex expressions in the "Expected fields"'),
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='json_extraction_root',
            field=models.CharField(blank=True, default='', help_text='The level in the data structure from which to extract. (optional)', max_length=200, verbose_name='Extraction Root'),
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='name',
            field=models.CharField(help_text='Internal name for this File Blueprint.', max_length=250),
        ),
        migrations.AlterField(
            model_name='fileuploader',
            name='combined_consent',
            field=models.BooleanField(default=False, help_text='If enabled, participants provide consent once for all data.', verbose_name='All-in-one consent'),
        ),
        migrations.AlterField(
            model_name='fileuploader',
            name='name',
            field=models.CharField(help_text='Internal name for this File Uploader.', max_length=250),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='comparison_value',
            field=models.TextField(blank=True, help_text='The value to compare the field against.'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='execution_order',
            field=models.IntegerField(help_text='The order in which rules are applied..'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='field',
            field=models.TextField(help_text='The field this rule applies to (without quotes).'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='name',
            field=models.CharField(help_text='A label for this rule (internal use only).', max_length=250),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='regex_field',
            field=models.BooleanField(default=False, help_text='Enable if the field name above is a regex pattern.'),
        ),
    ]
