# Generated by Django 5.2.10 on 2026-02-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0011_alter_blueprintfilepath_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationblueprint',
            name='csv_delimiter',
            field=models.CharField(blank=True, default='', help_text='The character that separates values in the CSV', max_length=10),
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='description',
            field=models.TextField(help_text='Blueprint description visible for participants', null=True),
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='file_uploader',
            field=models.ForeignKey(blank=True, help_text='The File Uploader through which the related file will be uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddm_datadonation.fileuploader', verbose_name='Associated File Uploader'),
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='name',
            field=models.CharField(help_text='Internal name for this File Blueprint', max_length=250),
        ),
        migrations.AlterField(
            model_name='fileuploader',
            name='combined_consent',
            field=models.BooleanField(default=False, help_text='If enabled, participants provide consent once for all data', verbose_name='All-in-one consent'),
        ),
        migrations.AlterField(
            model_name='fileuploader',
            name='name',
            field=models.CharField(help_text='Internal name for this File Uploader', max_length=250),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='comparison_value',
            field=models.TextField(blank=True, help_text='The value to compare the field against'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='execution_order',
            field=models.IntegerField(help_text='The order in which rules are applied'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='field',
            field=models.TextField(help_text='The field this rule applies to (without quotes)'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='name',
            field=models.CharField(help_text='A label for this rule (internal use only)', max_length=250),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='regex_field',
            field=models.BooleanField(default=False, help_text='Enable if the field name above is a regex pattern'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='replacement_value',
            field=models.TextField(blank=True, help_text='Only required for operation "Replace match (regex)"'),
        ),
    ]
