# Generated by Django 5.2.10 on 2026-07-15 07:57

import ddm.core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0012_alter_donationblueprint_csv_delimiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationblueprint',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Blueprint description visible for participants'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='regex_path',
            field=models.TextField(blank=True, default='', help_text='The path where the file is expected to be located in the uploaded ZIP folder. You can use Regex to, e.g., add wildcard characters or to match files in different languages. Consult the documentation for some examples.', validators=[ddm.core.utils.validators.validate_regex_pattern], verbose_name='File path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='comparison_operator',
            field=models.CharField(blank=True, choices=[('', 'Keep Field'), ('==', 'Equal (==)'), ('!=', 'Not Equal (!=)'), ('>', 'Greater than (>)'), ('<', 'Smaller than (<)'), ('>=', 'Greater than or equal (>=)'), ('<=', 'Smaller than or equal (<=)'), ('regex-delete-match', 'Delete match (regex)'), ('regex-replace-match', 'Replace match (regex)'), ('regex-delete-row', 'Delete row when match (regex)')], default='', max_length=24, verbose_name='Extraction Operator'),
            preserve_default=False,
        ),
    ]
