# Generated by Django 5.2.16 on 2026-07-16 11:06

from django.db import migrations, models


STATUS_TO_EXTRACTION_STATE = {
    "success": "DATA_EXTRACTED",
    "failed": "FAILED",
    "pending": "NOT_ATTEMPTED",
    "no data extracted": "NO_DATA_EXTRACTED",
}


def populate_data_extraction_state(apps, schema_editor):
    DataDonation = apps.get_model("ddm_datadonation", "DataDonation")

    donations = DataDonation.objects.exclude(status__isnull=True).only(
        "id", "status", "data_extraction_state"
    )

    to_update = []
    for donation in donations.iterator():
        raw_status = donation.status
        normalized = raw_status.strip().lower() if isinstance(raw_status, str) else ""
        donation.data_extraction_state = STATUS_TO_EXTRACTION_STATE.get(normalized, "")
        to_update.append(donation)

    DataDonation.objects.bulk_update(
        to_update, ["data_extraction_state"], batch_size=500
    )


def reverse_noop(apps, schema_editor):
    # No reverse mapping — status is untouched by this migration, so nothing
    # to restore. data_extraction_state is simply reset to the field default.
    DataDonation = apps.get_model("ddm_datadonation", "DataDonation")
    DataDonation.objects.update(data_extraction_state="")


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0013_alter_donationblueprint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadonation',
            name='data_extraction_state',
            field=models.CharField(blank=True, choices=[('DATA_EXTRACTED', 'Data Extracted'), ('NO_DATA_EXTRACTED', 'No Data Extracted'), ('NOT_ATTEMPTED', 'Not Attempted'), ('FAILED', 'Failed')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='datadonation',
            name='n_data_entries',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datadonation',
            name='status',
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(
            populate_data_extraction_state, reverse_code=reverse_noop
        ),
    ]
