# Generated by Django 5.2.16 on 2026-07-17 08:05

import django.db.models.deletion
from django.db import migrations, models


def populate_blueprint_field(apps, schema_editor):
    DonationBlueprint = apps.get_model("ddm_datadonation", "DonationBlueprint")
    ExtractionField = apps.get_model("ddm_datadonation", "ExtractionField")
    ProcessingRule = apps.get_model("ddm_datadonation", "ProcessingRule")

    blueprints = (
        DonationBlueprint.objects
        .all()
        .only("id")
        .prefetch_related("processingrule_set")
    )

    to_create = []
    rules_to_delete = []
    rules_to_update = []
    for blueprint in blueprints.iterator(chunk_size=500):
        processing_rules = blueprint.processingrule_set.all()
        fields = {}
        for rule in processing_rules:
            field_name = rule.field
            if field_name not in fields:
                fields[field_name] = {
                    "match_regex": False,
                    "keep_in_donation": False,
                }

            if rule.regex_field:
                fields[field_name]["match_regex"] = True

            if rule.comparison_operator == "":
                fields[field_name]["keep_in_donation"] = True
                rules_to_delete.append(rule.pk)

        for field_name, config in fields.items():
            to_create.append(
                ExtractionField(
                    blueprint=blueprint,
                    expected_name=field_name,
                    match_regex=config["match_regex"],
                    keep_in_donation=config["keep_in_donation"],
                )
            )

        # Renumber the surviving (non-deleted) rules.
        rule_order = 1
        for rule in sorted(processing_rules, key=lambda r: r.execution_order):
            if rule.pk in rules_to_delete:
                continue
            if rule.execution_order != rule_order:
                rule.execution_order = rule_order
                rules_to_update.append(rule)
            rule_order += 1

    ExtractionField.objects.bulk_create(to_create, batch_size=500)
    ProcessingRule.objects.filter(pk__in=rules_to_delete).delete()
    ProcessingRule.objects.bulk_update(rules_to_update, ["execution_order"], batch_size=500)


def reverse_populate_blueprint_field(apps, schema_editor):
    # NOTE: lossy reverse — original ProcessingRule.name and execution_order
    # were not preserved during the forward migration and cannot be restored.
    DonationBlueprint = apps.get_model("ddm_datadonation", "DonationBlueprint")
    ProcessingRule = apps.get_model("ddm_datadonation", "ProcessingRule")

    blueprints = (
        DonationBlueprint.objects
        .all()
        .only("id")
        .prefetch_related("extractionfield_set", "processingrule_set")
    )

    rules_to_create = []
    rules_to_update = []
    for blueprint in blueprints.iterator(chunk_size=500):
        keep_in_donation_fields = [
            f for f in blueprint.extractionfield_set.all() if f.keep_in_donation
        ]
        existing_rules = sorted(
            blueprint.processingrule_set.all(),
            key=lambda r: r.execution_order,
        )

        rule_order = 1
        for field in keep_in_donation_fields:
            rules_to_create.append(
                ProcessingRule(
                    blueprint=blueprint,
                    name=f"Keep {field.expected_name}",
                    field=field.expected_name,
                    regex_field=field.match_regex,
                    comparison_operator="",
                    execution_order=rule_order,
                )
            )
            rule_order += 1

        for rule in existing_rules:
            if rule.execution_order != rule_order:
                rule.execution_order = rule_order
                rules_to_update.append(rule)
            rule_order += 1

    ProcessingRule.objects.bulk_create(rules_to_create, batch_size=500)
    ProcessingRule.objects.bulk_update(rules_to_update, ["execution_order"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0014_datadonation_data_extraction_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationblueprint',
            name='exp_file_format',
            field=models.CharField(choices=[('json', 'JSON file'), ('csv', 'CSV file'), ('txt', 'Text file')], default='json', max_length=10, verbose_name='Expected file format'),
        ),
        migrations.CreateModel(
            name='ExtractionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_name', models.TextField(help_text='Pattern to match field that needs to be present in file')),
                ('match_regex', models.BooleanField(default=False)),
                ('keep_in_donation', models.BooleanField(default=False)),
                ('alias', models.CharField(blank=True, help_text='Optional internal name to store this field under, esp. useful when `expected name` is a regex pattern and you want a clean field name in the stored data structure rather than the value defined in `expected name`.', max_length=125)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddm_datadonation.donationblueprint')),
            ],
        ),
        migrations.RunPython(
            populate_blueprint_field, reverse_code=reverse_populate_blueprint_field
        ),
    ]
