# Generated by Django 5.2.16 on 2026-07-17 12:50

import django.db.models.deletion
from django.db import migrations, models


def reassign_processing_rule_field(apps, schema_editor):
    DonationBlueprint = apps.get_model("ddm_datadonation", "DonationBlueprint")
    ProcessingRule = apps.get_model("ddm_datadonation", "ProcessingRule")

    blueprints = (
        DonationBlueprint.objects
        .all()
        .only("id")
        .prefetch_related("processingrule_set", "extractionfield_set")
    )

    rules_to_update = []
    unmatched = []
    for blueprint in blueprints.iterator(chunk_size=500):
        processing_rules = blueprint.processingrule_set.all()
        extraction_fields = blueprint.extractionfield_set.all()

        field_lookup = {ef.expected_name: ef for ef in extraction_fields}

        for rule in processing_rules:
            matched_field = field_lookup.get(rule.field)
            rule.field_new = matched_field
            rules_to_update.append(rule)
            if matched_field is None:
                unmatched.append(rule.pk)

    ProcessingRule.objects.bulk_update(rules_to_update, ["field_new"], batch_size=500)

    if unmatched:
        print(
            f"WARNING: {len(unmatched)} ProcessingRule(s) could not be matched "
            f"to an ExtractionField and were left with field=None: {unmatched}"
        )


def reverse_reassign_processing_rule_field(apps, schema_editor):
    ProcessingRule = apps.get_model("ddm_datadonation", "ProcessingRule")

    rules = ProcessingRule.objects.select_related("field_new").all()

    rules_to_update = []
    unrecoverable = []
    for rule in rules.iterator(chunk_size=500):
        if rule.field_new_id is not None:
            rule.field = rule.field_new.expected_name
            rule.regex_field = rule.field_new.match_regex
        else:
            rule.field = ""
            rule.regex_field = False
            unrecoverable.append(rule.pk)
        rules_to_update.append(rule)

    ProcessingRule.objects.bulk_update(
        rules_to_update, ["field", "regex_field"], batch_size=500
    )

    if unrecoverable:
        print(
            f"WARNING: {len(unrecoverable)} ProcessingRule(s) had no matched "
            f"ExtractionField and their original `field`/`regex_field` values "
            f"could not be restored on reverse: {unrecoverable}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0015_alter_donationblueprint_exp_file_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingrule',
            name='comparison_operator',
            field=models.CharField(choices=[('==', 'Equal (==)'), ('!=', 'Not Equal (!=)'), ('>', 'Greater than (>)'), ('<', 'Smaller than (<)'), ('>=', 'Greater than or equal (>=)'), ('<=', 'Smaller than or equal (<=)'), ('regex-delete-match', 'Delete match (regex)'), ('regex-replace-match', 'Replace match (regex)'), ('regex-delete-row', 'Delete row when match (regex)')], max_length=24, verbose_name='Extraction Operator'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='field',
            field=models.TextField(null=True, blank=True, default=""),
        ),
        migrations.AddField(
            model_name='processingrule',
            name='field_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddm_datadonation.extractionfield'),
        ),
        migrations.RunPython(
            reassign_processing_rule_field, reverse_code=reverse_reassign_processing_rule_field
        ),
        migrations.RemoveField(
            model_name='processingrule',
            name='field',
        ),
        migrations.RenameField(
            model_name='processingrule',
            old_name='field_new',
            new_name='field',
        ),
        migrations.RemoveField(
            model_name='processingrule',
            name='regex_field',
        ),
    ]
