# Generated by Django 5.2.16 on 2026-08-03 11:57

from django.db import migrations, models


def reassign_parser_fields(apps, schema_editor):
    DonationBlueprint = apps.get_model("ddm_datadonation", "DonationBlueprint")

    blueprints = DonationBlueprint.objects.all().only(
        "id", "csv_delimiter", "json_extraction_root", "exp_file_format", "parser_config"
    )

    for bp in blueprints:
        if bp.exp_file_format == "json":
            bp.parser_config = {
                "format": "json",
                "extraction_root": bp.json_extraction_root,
            }
        elif bp.exp_file_format == "csv":
            bp.parser_config = {
                "format": "csv",
                "delimiter": bp.csv_delimiter,
            }

        bp.save()


def reverse_reassign_parser_fields(apps, schema_editor):
    DonationBlueprint = apps.get_model("ddm_datadonation", "DonationBlueprint")

    blueprints = DonationBlueprint.objects.all().only(
        "id", "csv_delimiter", "json_extraction_root", "exp_file_format", "parser_config"
    )

    for bp in blueprints:
        if bp.exp_file_format == "json":
            bp.json_extraction_root = bp.parser_config.get("extraction_root", "")
        elif bp.exp_file_format == "csv":
            bp.csv_delimiter = bp.parser_config.get("delimiter", "")
        bp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0016_remove_processingrule_regex_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationblueprint',
            name='parser_config',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
        migrations.RunPython(
            reassign_parser_fields, reverse_code=reverse_reassign_parser_fields
        ),
        migrations.RemoveField(
            model_name='donationblueprint',
            name='csv_delimiter',
        ),
        migrations.RemoveField(
            model_name='donationblueprint',
            name='json_extraction_root',
        ),
        migrations.AlterField(
            model_name='donationblueprint',
            name='exp_file_format',
            field=models.CharField(choices=[('json', 'JSON file'), ('csv', 'CSV file'), ('txt', 'TXT file')], default='json', max_length=10, verbose_name='Expected file format'),
        ),
    ]
