# Generated by Django 5.2.16 on 2026-08-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0017_remove_donationblueprint_csv_delimiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationblueprint',
            name='backup_for',
            field=models.ForeignKey(blank=True, help_text="If set, this blueprint is used as a fallback when the referenced blueprint's parser fails to extract data (either because it does not find the expected file or because it encounters an error).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backups', to='ddm_datadonation.donationblueprint'),
        ),
        migrations.AddField(
            model_name='donationblueprint',
            name='backup_priority',
            field=models.PositiveIntegerField(default=0, help_text="If a Blueprint has multiple backups, backup blueprints with lower priority values are tried first when the main blueprint's parser fails."),
        ),
    ]
