# Generated by Django 5.2.16 on 2026-08-10 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0018_donationblueprint_backup_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationblueprint',
            name='nested_expected_fields',
            field=models.TextField(blank=True, default='', help_text='Comma-separated, in double quotes: <code>"Field A", "Field B"</code>. Only used if a Nested loop path is configured (JSON format).', validators=[django.core.validators.RegexValidator('^((["][^"]+["]))(\\s*,\\s*((["][^"]+["])))*[,\\s]*$', message='Field must contain one or multiple comma separated strings. Strings must be enclosed in double quotes ("string").')], verbose_name='Nested expected fields'),
        ),
        migrations.AddField(
            model_name='donationblueprint',
            name='nested_expected_fields_regex_matching',
            field=models.BooleanField(default=False, help_text='Select if you use regex expressions in the "Nested expected fields"'),
        ),
        migrations.AddField(
            model_name='extractionfield',
            name='scope',
            field=models.CharField(choices=[('root', 'Root level'), ('nested', 'Nested level')], default='root', help_text='Whether this field is extracted from the top-level item, or from a nested sub-item (only relevant when a Nested loop path is set).', max_length=10),
        ),
        migrations.AlterField(
            model_name='extractionfield',
            name='expected_name',
            field=models.TextField(help_text='The name of the field to extract, as it appears in the file. To reach a value nested inside another field, separate the names with a dot, e.g. <code>message.author.role</code>. This only works when Regex is switched off.'),
        ),
    ]
