# Generated by Django 5.2.16 on 2026-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0019_donationblueprint_nested_expected_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationblueprint',
            name='nested_display_by_root_item',
            field=models.BooleanField(default=False, help_text='Select if the extracted entries of a nested extraction should be displayed to participants grouped by element. Per default, all entries are displayed combined as a long list.', verbose_name='Group entries by parent item'),
        ),
        migrations.AddField(
            model_name='donationblueprint',
            name='nested_entry_exclusion_allowed',
            field=models.BooleanField(default=False, help_text='Select if participants are allowed to exclude nested entries from the donation.', verbose_name='Allow item exclusion'),
        ),
    ]
