# Generated by Django 4.2.16 on 2025-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_projects', '0005_alter_donationproject_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationproject',
            name='custom_uploader_translations',
            field=models.JSONField(blank=True, help_text='Advanced option to overwrite default phrases and translations used in the data donation interface. Must be a dictionary with the locale shortcuts as keys (e.g., "de" or "en") associated to a dictionary holding the translations.', null=True),
        ),
    ]
