# Generated by Django 4.2.16 on 2025-06-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_projects', '0006_donationproject_custom_uploader_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationproject',
            name='custom_uploader_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced option to overwrite default phrases and translations used in the data donation interface. Must be a dictionary with the locale shortcuts as keys (e.g., "de" or "en") associated to a dictionary holding the translations.'),
        ),
    ]
