# Generated by Django 5.2.16 on 2026-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_projects', '0007_alter_donationproject_custom_uploader_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationproject',
            name='show_project_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationproject',
            name='redirect_target',
            field=models.CharField(blank=True, help_text='Always include <i>https://</i> in the redirect address. If URL parameter extraction is enabled for this project, you can include the extracted URL parameters in the redirect address as follows: "https://redirect.me/?redirectpara=<b>{{participant.data.url_param.URLParameter}}</b>".', max_length=2000, verbose_name='Redirect address'),
        ),
    ]
