# Generated by Django 5.2.16 on 2026-08-09 07:32

import ddm.core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_projects', '0008_donationproject_show_project_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationproject',
            name='background_color',
            field=models.CharField(default='#f8fafc', help_text='Background color of the participation interface pages.', max_length=9, validators=[ddm.core.utils.validators.validate_hex_color], verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='donationproject',
            name='primary_color',
            field=models.CharField(default='#007b74', help_text='Accent color used for buttons and highlights in the participation interface.', max_length=9, validators=[ddm.core.utils.validators.validate_hex_color], verbose_name='Primary Color'),
        ),
    ]
