# Generated by Django 5.2.16 on 2026-08-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_projects', '0009_donationproject_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationproject',
            name='custom_uploader_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced option to overwrite default phrases and translations used in the data donation interface. Must be a dictionary with the locale shortcuts as keys (e.g., "de" or "en") associated to a dictionary holding the translations. Placeholders in overridden phrases must use simple "{param}" substitution, matching the defaults being overwritten; other formatting syntax (e.g., pluralization or linked messages) is not supported.'),
        ),
    ]
