# Generated by Django 3.2.13 on 2023-05-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ddm', '0043_auto_20230525_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='PooledProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddm.donationproject')),
            ],
        ),
    ]
