# Generated by Django 3.2.13 on 2023-06-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0043_auto_20230525_1621'),
        ('ddm_pooled', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(max_length=24)),
                ('pool_donate', models.BooleanField(default=False)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddm.participant')),
                ('pooled_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddm_pooled.pooledproject')),
            ],
        ),
    ]
