# Generated by Django 3.2.13 on 2023-06-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_pooled', '0002_poolparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolparticipant',
            name='external_id',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
