# Generated by Django 3.2.13 on 2023-08-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_pooled', '0005_auto_20230620_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoolParticipant',
        ),
    ]
