# Runs a build test every time a commit is pushed to branch 'main'.

name: Test and Publish Python Package

on:
  push:
    branches: [ main ]

  workflow_run:
    workflows: [ Merge to Main ]
    types:
      - completed

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: [mysql]
        python-version: [3.8, 3.10.4]
        include:
          - db: mysql
            db_port: 3306
            db_engine: django.db.backends.mysql
            db_user: root

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ddmtestdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2 mysqlclient
          pip install -r test_project/dev_requirements.txt

      - name: Run Tests With ${{ matrix.db }}
        env:
          DB: ${{ matrix.db }}
          DB_ENGINE: ${{ matrix.db_engine }}
          DB_NAME: ddmtestdb
          DB_USER: ${{ matrix.db_user }}
          DB_PASSWORD: password
          DB_PORT: ${{ matrix.db_port }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python test_project/manage.py test ddm

  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Antora
        run: npm i antora

      - name: Install Antora Extensions
        run: npm i @antora/lunr-extension

      - name: Generate Site
        run: npx antora docs/antora-playbook.yml

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/site

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Generate new setup.cfg
        run: bash version_bump.sh

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
