# Generated by Django 4.2.16 on 2025-04-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_datadonation', '0006_alter_datadonation_consent'),
        ('ddm_logging', '0004_auto_20241026_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionlogentry',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ddm_datadonation.fileuploader'),
        ),
        migrations.AlterField(
            model_name='exceptionlogentry',
            name='exception_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
