# Generated by Django 5.2.10 on 2026-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_logging', '0005_exceptionlogentry_uploader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionlogentry',
            name='exception_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
